### ISSUE TITLE
Not original movie finger wagging image.

### ISSUE THREAD

**Issue by peterhendrick** [Sticktron/AhAhAh#2]
This tweak is so amazingly awesome!! Thank you for it.

The only thing I would change, is that this is not the original finger wagging image. I think the image you used was created later as an internet meme.

Is there anyway you can change that image to the one that was used in the movie? Where he's wearing an Elvis suit, and his mouth movements are ridiculously animated to match the sounds. You can find it here:  https://jurassicsystems.com/

**Comment by Sticktron** [comment]
I couldn't find a good original at the time, so I used that one :/

However, the tweak allows you to choose any video and/or background image you want. You can choose from items in your Camera Roll, or copy files straight onto your device if you're comfortable with using iFunbox or a similar program on your PC.

If/when I do release an update I will add the original to it as well.

Thanks for the link :)

**Comment by peterhendrick** [comment]
Awesome! Thanks for the workaround. I took some screen capture and got the video into the tweak. I got cocky and tried to get some of the command line in there too, but it didn't look too great. I'm gonna re-do it later and just get the finger wagging. If you'd like, I can share the .mp4 when I'm done and save you a little work for if you do an update.

**Comment by Sticktron** [comment]
Sure

**Comment by Sticktron** [comment]
Added original movie clip as new default theme.
