### ISSUE TITLE
Crashes immediately after entering incorrect passcode

### ISSUE THREAD

**Issue by captain-awesome** [Sticktron/AhAhAh#4]
The application crashes immediately after entering incorrect pass code.

Current settings:

```
Fullscreen video set to disabled
Video set to Ah! Ah! Ah!
Background image set to Bluescreen Error
Max failed attempts set to 1
TouchID fails set disabled
```

iPhone 6 Plus
iOS version 9.1

Please advise on how to fix the crashing issue.

**Comment by Sticktron** [comment]
Sorry, supports iOS 7-8 only.

Sent from my iPhone

On Apr 24, 2016, at 5:58 PM, captain-awesome <notifications@github.com<mailto:notifications@github.com>> wrote:

The application crashes immediately after entering incorrect pass code.

Current settings:

Fullscreen video set to disabled
Video set to Ah! Ah! Ah!
Background image set to Bluescreen Error
Max failed attempts set to 1
TouchID fails set disabled

iPhone 6 Plus
iOS version 9.1

Please advise on how to fix the crashing issue.

**Comment by captain-awesome** [comment]
Thanks for the prompt reply.

This app is too awesome!
Any potential support for iOS 9?

**Comment by Sticktron** [comment]
Version 2.0 beta supports iOS 9.

**Comment by captain-awesome** [comment]
Hi Sitcktron, thank you for updating this.

Is v 2.0 beta strictly for iOS 9 or iOS 9x?
How soon will this be available for Cydia?

Thanks

**Comment by Sticktron** [comment]
It supports iOS 7, 8, and 9 (up to 9.3.3, the latest jailbreakable version).

It's available in Cydia by adding sticktron.github.com/repohttp://sticktron.github.com/repo to your sources.

Sent from my iPhone

On Oct 3, 2016, at 11:59 AM, captain-awesome <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Sitcktron, thank you for updating this.

Is v 2.0 beta strictly for iOS 9 or iOS 9x?
How soon will this be available for Cydia?

Thanks

**Comment by captain-awesome** [comment]
Awesome, all is working.
Thank you so much for updating this.

Cheers!
